# External validation with known isoform-specific PPIs

We compare Splitpea’s rewired network built using rMATS data from the PC3E-GS689 dataset against IntAct's currated cancer interaction set. The network we use comes from the tutorial in /examples/condition_mode.ipynb in the rMATS example section. Please see that tutorial for details on how the network was built. Here we use the PC3E_GS689.edges.pickle file that was generated in that tutorial.

In [ ]:
import pandas as pd
import re 
import pickle

In [ ]:
# Download the IntAct cancer interaction set 
!wget https://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/datasets/Cancer.zip
!unzip Cancer.zip

# additional mapping file for organism id conversions
!wget https://raw.githubusercontent.com/ylaboratory/splitpea/master/reference/hsa_mapping_all.txt

In [ ]:
path = "Cancer.txt"
df = pd.read_csv(path, sep="\t", dtype=str, low_memory=False)

## Get isoform-specific PPIs from IntAct:

In [ ]:
UNIPROT_TOKEN_RE = re.compile(r"^uniprotkb:([A-Z0-9]{6,10}(?:-\d+)?)$", re.I)
ISOFORM_RE = re.compile(r"^[A-Z0-9]{6,10}-\d+$", re.I)

def edges_to_df(G, label: str):
    edges = list(G.edges())
    df = pd.DataFrame(edges, columns=["entrezA", "entrezB"])

    df["entrezA"] = pd.to_numeric(df["entrezA"], errors="ignore")
    df["entrezB"] = pd.to_numeric(df["entrezB"], errors="ignore")

    a = df["entrezA"]
    b = df["entrezB"]
    df["entrez1"] = a.where(a <= b, b)
    df["entrez2"] = b.where(a <= b, a)

    df = df[["entrez1", "entrez2"]].drop_duplicates()
    df[label] = True
    return df

def first_uniprot_id(field: str):
    if not isinstance(field, str) or not field:
        return None
    for tok in field.split("|"):
        tok = tok.strip()
        m = UNIPROT_TOKEN_RE.match(tok)
        if m:
            return m.group(1)
    return None

def is_isoform_acc(acc: str):
    return isinstance(acc, str) and bool(ISOFORM_RE.match(acc))

GENE_NAME_RE = re.compile(r"^(?:uniprotkb:)?([A-Za-z0-9_.-]+)\(gene name\)$", re.I)

def gene_from_aliases(alias_field: str):
    if not isinstance(alias_field, str) or not alias_field:
        return None
    for tok in alias_field.split("|"):
        tok = tok.strip()
        if "(gene name)" in tok.lower():
            m = GENE_NAME_RE.match(tok)
            if m:
                return m.group(1)
            base = tok.split("(")[0]
            if ":" in base:
                base = base.split(":", 1)[1]
            base = base.strip()
            if base:
                return base
    return None

df["uniprotA"] = df["#ID(s) interactor A"].map(first_uniprot_id)
df["uniprotB"] = df["ID(s) interactor B"].map(first_uniprot_id)

iso_mask = df["uniprotA"].map(is_isoform_acc) | df["uniprotB"].map(is_isoform_acc)
df_iso = df.loc[iso_mask].copy()

df_iso["geneA"] = df_iso["Alias(es) interactor A"].map(gene_from_aliases)
df_iso["geneB"] = df_iso["Alias(es) interactor B"].map(gene_from_aliases)

map_path = "hsa_mapping_all.txt"
hsa_map = pd.read_csv(map_path, sep="\t", dtype=str)
sym2entrez = hsa_map[["symbol", "entrez"]].copy()

sym2entrez["symbol"] = sym2entrez["symbol"].astype(str).str.strip()
sym2entrez["entrez"] = sym2entrez["entrez"].astype(str).str.strip()

sym2entrez = sym2entrez[sym2entrez["symbol"].ne("") & sym2entrez["symbol"].notna()].copy()

sym2entrez = sym2entrez.drop_duplicates(subset=["symbol"], keep="first").copy()
df_out = df_iso.copy()

for col in ["geneA", "geneB"]:
    df_out[col] = df_out[col].astype(str).str.strip()
    df_out.loc[df_out[col].isin(["", "nan", "None"]), col] = pd.NA

df_out = df_out.merge(
    sym2entrez.rename(columns={"symbol": "geneA", "entrez": "entrezA"}),
    on="geneA",
    how="left"
)

df_out = df_out.merge(
    sym2entrez.rename(columns={"symbol": "geneB", "entrez": "entrezB"}),
    on="geneB",
    how="left"
)

## Load Splitpea network

In [ ]:
# replace with path to the saved Splitpea prostate cancer network from tutorial (/examples/condition_mode.ipynb)
with open("PC3E_GS689.edges.pickle", "rb") as f:
    prostate_splitpea = pickle.load(f)
    
df_all = edges_to_df(prostate_splitpea, "in_splitpea")

df_all = df_all.rename(columns={"entrez1": "entrezA", "entrez2": "entrezB"})

## Standarize edges for comparision

In [ ]:
def canonicalize_edges(df, a="entrezA", b="entrezB"):
    out = df.copy()
    out[a] = pd.to_numeric(out[a], errors="coerce")
    out[b] = pd.to_numeric(out[b], errors="coerce")

    out["e1"] = out[[a, b]].min(axis=1)
    out["e2"] = out[[a, b]].max(axis=1)

    return out.dropna(subset=["e1", "e2"])

df_cons = canonicalize_edges(df_all, "entrezA", "entrezB")
df_intact = canonicalize_edges(df_out, "entrezA", "entrezB")

cons_edges = df_cons[["e1", "e2"]].drop_duplicates()
intact_edges = df_intact[["e1", "e2"]].drop_duplicates()

cons_keys = df_cons[["e1", "e2"]].drop_duplicates()
df_overlap= df_intact.merge(cons_keys, on=["e1", "e2"], how="inner")
df_overlap = df_overlap.dropna(subset=["entrezA", "entrezB"]).copy()

df_overlap

,#ID(s) interactor A,ID(s) interactor B,Alt. ID(s) interactor A,Alt. ID(s) interactor B,Alias(es) interactor A,Alias(es) interactor B,Interaction detection method(s),Publication 1st author(s),Publication Identifier(s),Taxid interactor A,...,Identification method participant A,Identification method participant B,uniprotA,uniprotB,geneA,geneB,entrezA,entrezB,e1,e2
11,uniprotkb:Q9H2D6-5,uniprotkb:Q9H2D6-5,intact:EBI-1023227,intact:EBI-1023227,psi-mi:q9h2d6-5(display_long)|uniprotkb:TRIOBP...,psi-mi:q9h2d6-5(display_long)|uniprotkb:TRIOBP...,"psi-mi:""MI:0071""(molecular sieving)",Li et al. (2007),pubmed:17629495|imex:IM-19091,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0816""(molecular weight estimation b...","psi-mi:""MI:0816""(molecular weight estimation b...",Q9H2D6-5,Q9H2D6-5,TRIOBP,TRIOBP,11078.0,11078.0,11078.0,11078.0
12,uniprotkb:P40337-3,uniprotkb:Q16665,intact:EBI-301270|intact:EBI-8411390|intact:MI...,intact:EBI-447269|uniprotkb:Q53XP6|uniprotkb:Q...,psi-mi:p40337-3(display_long)|uniprotkb:VHL19(...,psi-mi:hif1a_human(display_long)|uniprotkb:ARN...,"psi-mi:""MI:0018""(two hybrid)",Bex et al. (2007),pubmed:17986458,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",P40337-3,Q16665,VHL,HIF1A,7428.0,3091.0,3091.0,7428.0
13,uniprotkb:P40337-3,uniprotkb:Q16665,intact:EBI-301270|intact:EBI-8411390|intact:MI...,intact:EBI-447269|uniprotkb:Q53XP6|uniprotkb:Q...,psi-mi:p40337-3(display_long)|uniprotkb:VHL19(...,psi-mi:hif1a_human(display_long)|uniprotkb:ARN...,"psi-mi:""MI:0018""(two hybrid)",Bex et al. (2007),pubmed:17986458,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",P40337-3,Q16665,VHL,HIF1A,7428.0,3091.0,3091.0,7428.0
14,uniprotkb:P40337-3,uniprotkb:Q16665,intact:EBI-301270|intact:EBI-8411390|intact:MI...,intact:EBI-447269|uniprotkb:Q53XP6|uniprotkb:Q...,psi-mi:p40337-3(display_long)|uniprotkb:VHL19(...,psi-mi:hif1a_human(display_long)|uniprotkb:ARN...,"psi-mi:""MI:0018""(two hybrid)",Bex et al. (2007),pubmed:17986458,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",P40337-3,Q16665,VHL,HIF1A,7428.0,3091.0,3091.0,7428.0
15,uniprotkb:Q15369,uniprotkb:P40337-3,intact:EBI-301231|uniprotkb:Q567Q6|ensembl:ENS...,intact:EBI-301270|intact:EBI-8411390|intact:MI...,psi-mi:eloc_human(display_long)|uniprotkb:ELOC...,psi-mi:p40337-3(display_long)|uniprotkb:VHL19(...,"psi-mi:""MI:0018""(two hybrid)",Bex et al. (2007),pubmed:17986458,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0078""(nucleotide sequence identific...","psi-mi:""MI:0078""(nucleotide sequence identific...",Q15369,P40337-3,ELOC,VHL,6921.0,7428.0,6921.0,7428.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,uniprotkb:P04626,uniprotkb:Q99952-1,intact:EBI-641062|uniprotkb:Q14256|uniprotkb:Q...,intact:EBI-12739708|ensembl:ENSP00000175756.5,psi-mi:erbb2_human(display_long)|uniprotkb:p18...,psi-mi:q99952-1(display_long)|uniprotkb:Brain-...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Wang et al. (2014),pubmed:25081058|imex:IM-25721,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",P04626,Q99952-1,ERBB2,PTPN18,2064.0,26469.0,2064.0,26469.0
162,uniprotkb:Q99952-1,uniprotkb:P04626,intact:EBI-12739708|ensembl:ENSP00000175756.5,intact:EBI-641062|uniprotkb:Q14256|uniprotkb:Q...,psi-mi:q99952-1(display_long)|uniprotkb:Brain-...,psi-mi:erbb2_human(display_long)|uniprotkb:p18...,"psi-mi:""MI:0096""(pull down)",Wang et al. (2014),pubmed:25081058|imex:IM-25721,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q99952-1,P04626,PTPN18,ERBB2,26469.0,2064.0,2064.0,26469.0
163,uniprotkb:Q99952-1,uniprotkb:P04626,intact:EBI-12739708|ensembl:ENSP00000175756.5,intact:EBI-641062|uniprotkb:Q14256|uniprotkb:Q...,psi-mi:q99952-1(display_long)|uniprotkb:Brain-...,psi-mi:erbb2_human(display_long)|uniprotkb:p18...,"psi-mi:""MI:0096""(pull down)",Wang et al. (2014),pubmed:25081058|imex:IM-25721,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q99952-1,P04626,PTPN18,ERBB2,26469.0,2064.0,2064.0,26469.0
164,uniprotkb:Q02297-6,uniprotkb:P01133,intact:EBI-15651799|ensembl:ENSP00000287842.4,intact:EBI-640857|uniprotkb:B4DRK7|uniprotkb:E...,psi-mi:q02297-6(display_long)|uniprotkb:NRG1(g...,psi-mi:egf_human(display_long)|uniprotkb:EGF(g...,"psi-mi:""MI:0107""(surface plasmon resonance)",Freed et al. (2017),imex:IM-27745|pubmed:28988771,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",Q02297-6,P01133,NRG1,EGF,3084.0,1950.0,1950.0,3084.0
165,uniprotkb:Q07817-1,uniprotkb:Q07812,intact:EBI-287195|intact:EBI-8058735|intact:MI...,intact:EBI-516580|uniprotkb:P55269|uniprotkb:Q...,psi-mi:q07817-1(display_long)|uniprotkb:BCLX(g...,psi-mi:bax_human(display_long)|uniprotkb:BAX(g...,"psi-mi:""MI:0018""(two hybrid)",Chu et al. (2018),pubmed:29749471|imex:IM-29224,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",Q07817-1,Q07812,BCL2L1,BAX,598.0,581.0,581.0,598.0

In [ ]:
# only keep unqiue edges
tmp = df_overlap.copy()

tmp["_ia"] = tmp[["#ID(s) interactor A", "ID(s) interactor B"]].min(axis=1)
tmp["_ib"] = tmp[["#ID(s) interactor A", "ID(s) interactor B"]].max(axis=1)

df_overlap_norepeats = (
    tmp.drop_duplicates(subset=["_ia", "_ib"], keep="first")
       .drop(columns=["_ia", "_ib"])
       .copy()
)
df_overlap_norepeats

,#ID(s) interactor A,ID(s) interactor B,Alt. ID(s) interactor A,Alt. ID(s) interactor B,Alias(es) interactor A,Alias(es) interactor B,Interaction detection method(s),Publication 1st author(s),Publication Identifier(s),Taxid interactor A,...,Identification method participant A,Identification method participant B,uniprotA,uniprotB,geneA,geneB,entrezA,entrezB,e1,e2
11,uniprotkb:Q9H2D6-5,uniprotkb:Q9H2D6-5,intact:EBI-1023227,intact:EBI-1023227,psi-mi:q9h2d6-5(display_long)|uniprotkb:TRIOBP...,psi-mi:q9h2d6-5(display_long)|uniprotkb:TRIOBP...,"psi-mi:""MI:0071""(molecular sieving)",Li et al. (2007),pubmed:17629495|imex:IM-19091,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0816""(molecular weight estimation b...","psi-mi:""MI:0816""(molecular weight estimation b...",Q9H2D6-5,Q9H2D6-5,TRIOBP,TRIOBP,11078.0,11078.0,11078.0,11078.0
12,uniprotkb:P40337-3,uniprotkb:Q16665,intact:EBI-301270|intact:EBI-8411390|intact:MI...,intact:EBI-447269|uniprotkb:Q53XP6|uniprotkb:Q...,psi-mi:p40337-3(display_long)|uniprotkb:VHL19(...,psi-mi:hif1a_human(display_long)|uniprotkb:ARN...,"psi-mi:""MI:0018""(two hybrid)",Bex et al. (2007),pubmed:17986458,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",P40337-3,Q16665,VHL,HIF1A,7428.0,3091.0,3091.0,7428.0
15,uniprotkb:Q15369,uniprotkb:P40337-3,intact:EBI-301231|uniprotkb:Q567Q6|ensembl:ENS...,intact:EBI-301270|intact:EBI-8411390|intact:MI...,psi-mi:eloc_human(display_long)|uniprotkb:ELOC...,psi-mi:p40337-3(display_long)|uniprotkb:VHL19(...,"psi-mi:""MI:0018""(two hybrid)",Bex et al. (2007),pubmed:17986458,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0078""(nucleotide sequence identific...","psi-mi:""MI:0078""(nucleotide sequence identific...",Q15369,P40337-3,ELOC,VHL,6921.0,7428.0,6921.0,7428.0
17,uniprotkb:P40337-3,uniprotkb:Q99814,intact:EBI-301270|intact:EBI-8411390|intact:MI...,intact:EBI-447470|uniprotkb:Q86VA2|uniprotkb:Q...,psi-mi:p40337-3(display_long)|uniprotkb:VHL19(...,psi-mi:epas1_human(display_long)|uniprotkb:EPA...,"psi-mi:""MI:0018""(two hybrid)",Bex et al. (2007),pubmed:17986458,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0078""(nucleotide sequence identific...","psi-mi:""MI:0078""(nucleotide sequence identific...",P40337-3,Q99814,VHL,EPAS1,7428.0,2034.0,2034.0,7428.0
18,uniprotkb:P41134,uniprotkb:P15923-1,intact:EBI-1215527|uniprotkb:O00651|uniprotkb:...,intact:EBI-769645|ensembl:ENSP00000262965.5,psi-mi:id1_human(display_long)|uniprotkb:ID1(g...,psi-mi:p15923-1(display_long)|uniprotkb:PAN-2(...,"psi-mi:""MI:0018""(two hybrid)",Terai et al. (2000),pubmed:10915743|imex:IM-19434,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0078""(nucleotide sequence identific...","psi-mi:""MI:0078""(nucleotide sequence identific...",P41134,P15923-1,ID1,TCF3,3397.0,6929.0,3397.0,6929.0
19,uniprotkb:Q02363,uniprotkb:P15923-1,intact:EBI-713450|ensembl:ENSP00000234091.4|en...,intact:EBI-769645|ensembl:ENSP00000262965.5,psi-mi:id2_human(display_long)|uniprotkb:Inhib...,psi-mi:p15923-1(display_long)|uniprotkb:PAN-2(...,"psi-mi:""MI:0018""(two hybrid)",Terai et al. (2000),pubmed:10915743|imex:IM-19434,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0078""(nucleotide sequence identific...","psi-mi:""MI:0078""(nucleotide sequence identific...",Q02363,P15923-1,ID2,TCF3,3398.0,6929.0,3398.0,6929.0
20,uniprotkb:P15923-1,uniprotkb:Q02535,intact:EBI-769645|ensembl:ENSP00000262965.5,intact:EBI-1387094|uniprotkb:O75641|uniprotkb:...,psi-mi:p15923-1(display_long)|uniprotkb:PAN-2(...,psi-mi:id3_human(display_long)|uniprotkb:ID3(g...,"psi-mi:""MI:0018""(two hybrid)",Terai et al. (2000),pubmed:10915743|imex:IM-19434,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0078""(nucleotide sequence identific...","psi-mi:""MI:0078""(nucleotide sequence identific...",P15923-1,Q02535,TCF3,ID3,6929.0,3399.0,3399.0,6929.0
22,uniprotkb:P15923-1,uniprotkb:P15172,intact:EBI-769645|ensembl:ENSP00000262965.5,intact:EBI-488878|uniprotkb:O75321|ensembl:ENS...,psi-mi:p15923-1(display_long)|uniprotkb:PAN-2(...,psi-mi:myod1_human(display_long)|uniprotkb:Myo...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Terai et al. (2000),pubmed:10915743|imex:IM-19434,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0705""(anti tag western blot)","psi-mi:""MI:0705""(anti tag western blot)",P15923-1,P15172,TCF3,MYOD1,6929.0,4654.0,4654.0,6929.0
25,uniprotkb:P15923-1,uniprotkb:P15923-1,intact:EBI-769645|ensembl:ENSP00000262965.5,intact:EBI-769645|ensembl:ENSP00000262965.5,psi-mi:p15923-1(display_long)|uniprotkb:PAN-2(...,psi-mi:p15923-1(display_long)|uniprotkb:PAN-2(...,"psi-mi:""MI:0096""(pull down)",Terai et al. (2000),pubmed:10915743|imex:IM-19434,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0821""(molecular weight estimation b...","psi-mi:""MI:0821""(molecular weight estimation b...",P15923-1,P15923-1,TCF3,TCF3,6929.0,6929.0,6929.0,6929.0
27,uniprotkb:P04049,uniprotkb:P01116-2,intact:EBI-365996|uniprotkb:B0LPH8|uniprotkb:Q...,intact:EBI-367427|uniprotkb:P01118-1|ensembl:E...,psi-mi:raf1_human(display_long)|uniprotkb:RAF1...,psi-mi:p01116-2(display_long)|uniprotkb:KRAS(g...,"psi-mi:""MI:0096""(pull down)",Alvarez-Moya et al. (2010),pubmed:20802526|imex:IM-15312,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0705""(anti tag western blot)","psi-mi:""MI:0705""(anti tag western blot)",P04049,P01116-2,RAF1,KRAS,5894.0,3845.0,3845.0,5894.0
33,uniprotkb:Q13362-1,uniprotkb:P30153,intact:EBI-1266170|ensembl:ENSP00000333905.4,intact:EBI-302388|uniprotkb:Q13773|uniprotkb:Q...,psi-mi:q13362-1(display_long)|uniprotkb:PPP2R5...,psi-mi:2aaa_human(display_long)|uniprotkb:PPP2...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Shouse et al. (2011),pubmed:21460856|imex:IM-20860,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q13362-1,P30153,PPP2R5C,PPP2R1A,5527.0,5518.0,5518.0,5527.0
35,uniprotkb:Q13362-1,uniprotkb:P67775,intact:EBI-1266170|ensembl:ENSP00000333905.4,intact:EBI-712311|uniprotkb:P05323|uniprotkb:P...,psi-mi:q13362-1(display_long)|uniprotkb:PPP2R5...,psi-mi:pp2aa_human(display_long)|uniprotkb:PPP...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Shouse et al. (2011),pubmed:21460856|imex:IM-20860,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q13362-1,P67775,PPP2R5C,PPP2CA,5527.0,5515.0,5515.0,5527.0
36,uniprotkb:P08151,uniprotkb:P23443-2,intact:EBI-308084|uniprotkb:Q8TDN9|uniprotkb:D...,intact:EBI-6093204,psi-mi:gli1_human(display_long)|uniprotkb:GLI1...,psi-mi:p23443-2(display_long)|uniprotkb:Riboso...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Wang et al. (2012),imex:IM-17321|pubmed:22439934,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",P08151,P23443-2,GLI1,RPS6KB1,2735.0,6198.0,2735.0,6198.0
38,uniprotkb:O14786-2,uniprotkb:P15692-4,intact:EBI-6285281|ensembl:ENSP00000363955.4,intact:EBI-1026691|ensembl:ENSP00000429643.1,psi-mi:o14786-2(display_long)|uniprotkb:Solubl...,psi-mi:p15692-4(display_long)|uniprotkb:VEGF(i...,"psi-mi:""MI:0030""(cross-linking study)",Cecchi et al. (2012),pubmed:22897854|imex:IM-17719,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",O14786-2,P15692-4,NRP1,VEGFA,8829.0,7422.0,7422.0,8829.0
42,uniprotkb:P01112,uniprotkb:O00329-2,intact:EBI-350145|uniprotkb:Q9BR65|uniprotkb:Q...,intact:EBI-6470902|ensembl:ENSP00000513886.1,psi-mi:rash_human(display_long)|uniprotkb:HRAS...,psi-mi:o00329-2(display_long)|uniprotkb:p37-de...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Fransson et al. (2012),imex:IM-18635|pubmed:22020336,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",P01112,O00329-2,HRAS,PIK3CD,3265.0,5293.0,3265.0,5293.0
44,uniprotkb:P11362-14,uniprotkb:P09038,intact:EBI-6622185|ensembl:ENSP00000327229.6,intact:EBI-977447|uniprotkb:A4LBB8|uniprotkb:O...,psi-mi:p11362-14(display_long)|uniprotkb:I(iso...,psi-mi:fgf2_human(display_long)|uniprotkb:Basi...,"psi-mi:""MI:0099""(scintillation proximity assay)",Bono et al. (2013),pubmed:23597562|imex:IM-20536,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0421""(identification by antibody)","psi-mi:""MI:0421""(identification by antibody)",P11362-14,P09038,FGFR1,FGF2,2260.0,2247.0,2247.0,2260.0
48,uniprotkb:Q16539-3,uniprotkb:P28482,intact:EBI-6932370|intact:EBI-7234165|intact:M...,intact:EBI-959949|uniprotkb:A8CZ64|ensembl:ENS...,psi-mi:q16539-3(display_long)|uniprotkb:MAPK14...,psi-mi:mk01_human(display_long)|uniprotkb:MAPK...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",von et al. (2012),imex:IM-21255|pubmed:22521293,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q16539-3,P28482,MAPK14,MAPK1,1432.0,5594.0,1432.0,5594.0
108,uniprotkb:P04049-1,uniprotkb:Q02750,intact:EBI-9549505|ensembl:ENSP00000251849.4|e...,intact:EBI-492564|ensembl:ENSP00000302486.5,psi-mi:p04049-1(display_long)|uniprotkb:6C(iso...,psi-mi:mp2k1_human(display_long)|uniprotkb:ERK...,"psi-mi:""MI:0107""(surface plasmon resonance)",Lito et al. (2014),pubmed:24746704|imex:IM-22983,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",P04049-1,Q02750,RAF1,MAP2K1,5894.0,5604.0,5604.0,5894.0
109,uniprotkb:P29353-7,uniprotkb:P21860,intact:EBI-9691288|ensembl:ENSP00000357438.4,intact:EBI-720706|uniprotkb:A8K6L6|uniprotkb:B...,psi-mi:p29353-7(display_long)|uniprotkb:SHC1(g...,psi-mi:erbb3_human(display_long)|uniprotkb:Tyr...,"psi-mi:""MI:0112""(ubiquitin reconstruction)",Petschnigg et al. (2014),pubmed:24658140|imex:IM-23090,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",P29353-7,P21860,SHC1,ERBB3,6464.0,2065.0,2065.0,6464.0
110,uniprotkb:Q8NHY2-1,uniprotkb:Q13619,intact:EBI-9698228|ensembl:ENSP00000356641.3,intact:EBI-456106|uniprotkb:O75834|uniprotkb:Q...,psi-mi:q8nhy2-1(display_long)|uniprotkb:COP1(g...,psi-mi:cul4a_human(display_long)|uniprotkb:CUL...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Lu et al. (2014),pubmed:25117710|imex:IM-23043,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q8NHY2-1,Q13619,COP1,CUL4A,64326.0,8451.0,8451.0,64326.0
111,uniprotkb:Q8NHY2-1,uniprotkb:Q16531,intact:EBI-9698228|ensembl:ENSP00000356641.3,intact:EBI-350322|uniprotkb:A6NG77|uniprotkb:O...,psi-mi:q8nhy2-1(display_long)|uniprotkb:COP1(g...,psi-mi:ddb1_human(display_long)|uniprotkb:DDB1...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Lu et al. (2014),pubmed:25117710|imex:IM-23043,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q8NHY2-1,Q16531,COP1,DDB1,64326.0,1642.0,1642.0,64326.0
138,uniprotkb:P25963,uniprotkb:Q04206-1,intact:EBI-307386|ensembl:ENSP00000216797.6|un...,intact:EBI-10826776|ensembl:ENSP00000384273.3,psi-mi:ikba_human(display_long)|uniprotkb:MAD3...,psi-mi:q04206-1(display_long)|uniprotkb:Nuclea...,"psi-mi:""MI:0417""(footprinting)",Liu et al. (2015),imex:IM-24472|pubmed:25759022,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0427""(Identification by mass spectr...","psi-mi:""MI:0427""(Identification by mass spectr...",P25963,Q04206-1,NFKBIA,RELA,4792.0,5970.0,4792.0,5970.0
148,uniprotkb:Q13153,uniprotkb:Q05513-1,intact:EBI-1307|uniprotkb:O75561|uniprotkb:Q13...,intact:EBI-11165771|ensembl:ENSP00000367830.3,psi-mi:pak1_human(display_long)|uniprotkb:PAK1...,psi-mi:q05513-1(display_long)|uniprotkb:nPKC-z...,"psi-mi:""MI:0096""(pull down)",Jinesh et al. (2016),pubmed:23175184|pubmed:unassigned1271|imex:IM-...,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q13153,Q05513-1,PAK1,PRKCZ,5058.0,5590.0,5058.0,5590.0
150,uniprotkb:Q13153,uniprotkb:Q05513-2,intact:EBI-1307|uniprotkb:O75561|uniprotkb:Q13...,intact:EBI-11165935|ensembl:ENSP00000383712.2,psi-mi:pak1_human(display_long)|uniprotkb:PAK1...,psi-mi:q05513-2(display_long)|uniprotkb:nPKC-z...,"psi-mi:""MI:0096""(pull down)",Jinesh et al. (2016),pubmed:23175184|pubmed:unassigned1271|imex:IM-...,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",Q13153,Q05513-2,PAK1,PRKCZ,5058.0,5590.0,5058.0,5590.0
156,uniprotkb:P11362,uniprotkb:P09038-2,intact:EBI-1028277|uniprotkb:P17049|uniprotkb:...,intact:EBI-11122080|ensembl:ENSP00000477134.1|...,psi-mi:fgfr1_human(display_long)|uniprotkb:FGF...,psi-mi:p09038-2(display_long)|uniprotkb:FGF2(g...,"psi-mi:""MI:0107""(surface plasmon resonance)",Ronca et al. (2015),pubmed:26267536|imex:IM-24965,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",P11362,P09038-2,FGFR1,FGF2,2260.0,2247.0,2247.0,2260.0
157,uniprotkb:P52799,uniprotkb:P54760-1,intact:EBI-7532268|intact:MINT-3019741|uniprot...,intact:EBI-11565809|ensembl:ENSP00000350896.3,psi-mi:efnb2_human(display_long)|uniprotkb:EFN...,psi-mi:p54760-1(display_long)|uniprotkb:Hepato...,"psi-mi:""MI:1247""(microscale thermophoresis)",Pradeep et al. (2015),pubmed:26481148|imex:IM-25004,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",P52799,P54760-1,EFNB2,EPHB4,1948.0,2050.0,1948.0,2050.0
159,uniprotkb:P04626,uniprotkb:Q99952-1,intact:EBI-641062|uniprotkb:Q14256|uniprotkb:Q...,intact:EBI-12739708|ensembl:ENSP00000175756.5,psi-mi:erbb2_human(display_long)|uniprotkb:p18...,psi-mi:q99952-1(display_long)|uniprotkb:Brain-...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Wang et al. (2014),pubmed:25081058|imex:IM-25721,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0113""(western blot)","psi-mi:""MI:0113""(western blot)",P04626,Q99952-1,ERBB2,PTPN18,2064.0,26469.0,2064.0,26469.0
164,uniprotkb:Q02297-6,uniprotkb:P01133,intact:EBI-15651799|ensembl:ENSP00000287842.4,intact:EBI-640857|uniprotkb:B4DRK7|uniprotkb:E...,psi-mi:q02297-6(display_long)|uniprotkb:NRG1(g...,psi-mi:egf_human(display_long)|uniprotkb:EGF(g...,"psi-mi:""MI:0107""(surface plasmon resonance)",Freed et al. (2017),imex:IM-27745|pubmed:28988771,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",Q02297-6,P01133,NRG1,EGF,3084.0,1950.0,1950.0,3084.0
165,uniprotkb:Q07817-1,uniprotkb:Q07812,intact:EBI-287195|intact:EBI-8058735|intact:MI...,intact:EBI-516580|uniprotkb:P55269|uniprotkb:Q...,psi-mi:q07817-1(display_long)|uniprotkb:BCLX(g...,psi-mi:bax_human(display_long)|uniprotkb:BAX(g...,"psi-mi:""MI:0018""(two hybrid)",Chu et al. (2018),pubmed:29749471|imex:IM-29224,taxid:9606(human)|taxid:9606(Homo sapiens),...,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)",Q07817-1,Q07812,BCL2L1,BAX,598.0,581.0,581.0,598.0

In [ ]:
df_overlap_norepeats.to_csv("prosate_intact_overlap.tsv", sep="\t", index=False)

## Hypergeometric test for enrichment of isoform-specific PPIs in Splitpea rewired network

In [ ]:
from scipy.stats import hypergeom

N = 787570  # possible edges from reference PPI (splitpea/src/reference/human_ppi_0.5.dat)
K = 730     # isoform-specific PPIs in IntAct
n = 17012   # edges in Splitpea rewired network
k = 29      # overlapping edges between Splitpea rewired network and IntAct isoform-specific PPIs

p_over = hypergeom.sf(k-1, N, K, n)  
print(p_over)

0.0015682229616878801